name: "Sample Release"

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
      - run: |-
          echo '${{ toJSON(github) }}'
  ci-run:
    needs: "debug"
    uses: "Jikoo/ActionsTest/.github/workflows/ci.yml@main"
