name: "Sample Text"

on:
  push:
  workflow_dispatch:

jobs:
  debug:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    runs-on: "ubuntu-latest"
    steps:
    - run: "echo '${{ toJSON(github) }}'"
  ci-run:
    needs: "debug"
    uses: "Jikoo/ActionsTest/.github/workflows/ci.yml@main"
